// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuxitysivxryjhchvakg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eGl0eXNpdnhyeWpoY2h2YWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NzU2ODEsImV4cCI6MjA1ODM1MTY4MX0.ZVwxJw-p0IOgR-r5nhxvuRES00UAZKJwFvOTFFuJ_Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);